<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar</name>
   <tag></tag>
   <elementGuidId>357d230f-8138-45e6-b2a0-f5021a06737f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-primary.mb-20.mt-20.font-600.pl-40.pr-40.border-radius-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d77b5874-b1f2-4cfa-9847-ae40ef251015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>417afdf8-52c3-433b-a12b-e8131ad038b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary mb-20 mt-20 font-600 pl-40 pr-40 border-radius-5</value>
      <webElementGuid>006d25f0-11cc-409d-8937-8500e21a5dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Daftar
                </value>
      <webElementGuid>699d5334-6aa5-4dbf-9767-2c94acaff7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;section-register&quot;]/div[@class=&quot;container-custom&quot;]/div[@class=&quot;row justify-content-center mt-50&quot;]/div[@class=&quot;col-sm-10 col-md-7 col-lg-5&quot;]/span[1]/form[1]/div[@class=&quot;text-center&quot;]/button[@class=&quot;btn-primary mb-20 mt-20 font-600 pl-40 pr-40 border-radius-5&quot;]</value>
      <webElementGuid>a856ab8b-d44e-42d2-a66d-cbd9011fdbb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>caeeba8f-2dbf-4f81-8db5-3939b7ec75a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/div[2]/div/span/form/div[6]/button</value>
      <webElementGuid>1ea833a0-36a3-4df4-a3a7-0b03e4f24cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::button[1]</value>
      <webElementGuid>4f61e596-cd83-405a-9021-c1fb0d9a9096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketentuan Layanan'])[1]/following::button[1]</value>
      <webElementGuid>d09a9069-19ec-46bd-b071-2b40ca21f374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Enkripsi Teknologi Handal'])[1]/preceding::button[1]</value>
      <webElementGuid>986a3bfa-05f3-4458-b185-89c0e345e76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>89ef3d7b-8cd3-4f4f-a678-ff3aa7a61147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>a2648c2c-315e-4ad3-9f1d-30770092fb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                  Daftar
                ' or . = '
                  Daftar
                ')]</value>
      <webElementGuid>5ad1a46a-ca53-4f13-b981-42b3cde20ff0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
